config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from digital_library.users.views import home_view
urlpatterns = [
    path("", home_view, name="home"),
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("digital_library.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    path('game/', include('digital_library.game.urls', namespace='game')),
    path('books/', include('digital_library.books.urls', namespace='books')),
    path('clubs/', include('digital_library.clubs.urls', namespace='clubs')),
    path('events/', include('digital_library.events.urls', namespace='events')),
    path('archives/', include('digital_library.archives.urls', namespace='archives')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

digital_library/archives/urls.py
from django.urls import path
from . import views

app_name = 'archives'

urlpatterns = [
    path('', views.archive_list, name='archive_list'),
    path('create/', views.archive_create, name='archive_create'),
    path('<int:pk>/', views.archive_detail, name='archive_detail'),
    path('<int:pk>/update/', views.archive_update, name='archive_update'),
    path('<int:pk>/delete/', views.archive_delete, name='archive_delete'),
]

digital_library/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('search/', views.search_results, name='search_results'),

    path('create/', views.BookFormView.as_view(), name='book_create'),
    path('<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/update/', views.BookUpdateFormView.as_view(), name='book_update'),

    path('books/<int:book_id>/request/', views.create_exchange_request, name='create_exchange_request'),
    path('pending-requests/', views.pending_requests, name='pending_requests'),
    path('accept-request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject-request/<int:request_id>/', views.reject_request, name='reject_request'),

    path('shared-progress/', views.shared_progress, name='shared_progress'),
    path('finished-books/', views.finished_books, name='finished_books'),
    path('finished-books/remove/<int:book_id>/', views.remove_finished_book, name='remove_finished_book'),

    path('bookshelf/', views.profile_bookshelf, name='profile_bookshelf'),
    path('book/<int:book_id>/progress/', views.add_edit_progress, name='add_edit_progress'),
    path('book/<int:book_id>/finished/', views.add_to_finished_books, name='add_to_finished_books'),
    path('book/<int:book_id>/toggle_visibility/', views.toggle_visibility, name='toggle_visibility'),
    path('progress/<int:book_id>/toggle_visibility/', views.toggle_progress_visibility, name='toggle_progress_visibility'),

    path('<int:book_id>/discussions/start/', views.start_discussion, name='start_discussion'),
    path('<int:book_id>/discussions/', views.discussion_list, name='discussion_list'),
    path('<int:book_id>/discussions/<int:discussion_id>/', views.discussion_detail, name='discussion_detail'),
    path('discussions/<int:discussion_id>/comment/', views.add_comment, name='add_comment'),
    path('discussions/<int:discussion_id>/comment/<int:comment_id>/reply/', views.reply_comment, name='reply_comment'),

    # path('<int:id>/delete/', views.book_delete, name='book_delete'),
]

digital_library/clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('', views.club_list, name='club_list'),
    path('create/', views.club_create, name='club_create'),
    path('<int:club_id>/', views.club_detail, name='club_detail'),
    # path('<int:id>/update/', views.club_update, name='club_update'),
    # path('<int:id>/delete/', views.club_delete, name='club_delete'),
    path('<int:club_id>/post/create/', views.club_post_create, name='club_post_create'),
    path('<int:club_id>/request-to-join/', views.request_to_join, name='request_to_join'),
    path('<int:club_id>/manage-requests/', views.manage_membership_requests, name='manage_membership_requests'),
]

digital_library/events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('', views.event_list, name='event_list'),
    path('<int:pk>/', views.event_detail, name='event_detail'),
    path('<int:pk>/join/', views.join_event, name='join_event'),
    path('create/', views.create_event, name='create_event'),
    # path('<int:id>/update/', views.event_update, name='event_update'),
    # path('<int:id>/delete/', views.event_delete, name='event_delete'),
]

digital_library/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('select-book/', views.select_book, name='select_book'),
    path('<int:book_id>/<str:language>/ask/', views.ask_question, name='ask_question'),
    path('<int:book_id>/ask/', views.ask_local_question, name='ask_local_question'),
    path('submit-answer/', views.submit_answer, name='submit_answer'),
    path('result/', views.show_result, name='show_result'),
    path('restart/', views.restart_game, name='restart_game'),
    path('<int:book_id>/ratings/', views.view_ratings, name='view_ratings'),
    path('error/', views.error_page, name='error'),
]

digital_library/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

digital_library/archives/models.py
from django.db import models
from django.contrib.auth import get_user_model


class DigitalArchive(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    uploaded_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    file = models.FileField(upload_to='archives/')

    def __str__(self):
        return self.title

digital_library/events/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Event(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateTimeField()
    poster = models.ImageField(upload_to='event_posters/', blank=True, null=True)
    creator = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    participants = models.ManyToManyField(get_user_model(), related_name='events')

    def __str__(self):
        return self.title

digital_library/archives/forms.py
from django import forms
from .models import DigitalArchive

class ArchiveForm(forms.ModelForm):
    class Meta:
        model = DigitalArchive
        fields = ['title', 'description', 'file']

digital_library/books/forms.py
from django import forms
from .models import ExchangeRequest, Book, UserBookProgress, UserFinishedBook, Comment, Discussion


class ExchangeRequestForm(forms.ModelForm):
    class Meta:
        model = ExchangeRequest
        fields = ['message']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'cover_image', 'isbn', 'language']

    def clean_isbn(self):
        isbn = self.cleaned_data.get('isbn')
        if not isbn:
            raise forms.ValidationError("ISBN is required")
        if Book.objects.filter(isbn=isbn).exists():
            raise forms.ValidationError("A book with this ISBN already exists.")
        return isbn


class UpdateProgressForm(forms.ModelForm):
    class Meta:
        model = UserBookProgress
        fields = ['progress']


class AddFinishedBookForm(forms.ModelForm):
    class Meta:
        model = UserFinishedBook
        fields = []


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class DiscussionForm(forms.ModelForm):
    class Meta:
        model = Discussion
        fields = ['title']

digital_library/clubs/forms.py
# forms.py
from django import forms
from .models import Club, ClubPost

from ckeditor_uploader.widgets import CKEditorUploadingWidget


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['name', 'description']


class ClubPostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = ClubPost
        fields = ['content']

digital_library/events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'poster']

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

digital_library/archives/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import DigitalArchive
from .forms import ArchiveForm  # You need to create this form


@login_required
def archive_list(request):
    query = request.GET.get('q')
    if query:
        archives = DigitalArchive.objects.filter(title__icontains=query)
    else:
        archives = DigitalArchive.objects.all()

    return render(request, 'archives/archive_list.html', {'archives': archives})


@login_required
def archive_detail(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    return render(request, 'archives/archive_detail.html', {'archive': archive})


@login_required
def archive_create(request):
    if request.method == 'POST':
        form = ArchiveForm(request.POST, request.FILES)
        if form.is_valid():
            archive = form.save(commit=False)
            archive.uploaded_by = request.user
            archive.save()
            return redirect('archives:archive_list')
    else:
        form = ArchiveForm()
    return render(request, 'archives/archive_create.html', {'form': form})


@login_required
def archive_update(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    if request.method == 'POST':
        form = ArchiveForm(request.POST, request.FILES, instance=archive)
        if form.is_valid():
            form.save()
            return redirect('archives:archive_detail', pk=archive.pk)
    else:
        form = ArchiveForm(instance=archive)
    return render(request, 'archives/archive_create.html', {'form': form})


@login_required
def archive_delete(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    if request.method == 'POST':
        archive.delete()
        return redirect('archive_list')
    return render(request, 'archives/archive_confirm_delete.html', {'archive': archive})

digital_library/clubs/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import ClubPostForm, ClubForm
from .models import Club, ClubPost, ClubMembershipRequest


@login_required
def club_list(request):
    clubs = Club.objects.all()

    club_status = []
    for club in clubs:
        is_member = request.user in club.members.all()
        membership_request = ClubMembershipRequest.objects.filter(club=club, user=request.user,
                                                                  status='pending').exists()
        club_status.append({
            'club': club,
            'is_member': is_member,
            'membership_requested': membership_request
        })

    return render(request, 'clubs/club_list.html', {'club_status': club_status})


@login_required
def club_detail(request, club_id):
    club = get_object_or_404(Club, id=club_id)

    # Check if the user is a member of the club
    if request.user not in club.members.all():
        return render(request, 'error.html', {
            'message': 'You do not have permission to view this club.'
        })

    posts = club.posts.all()
    return render(request, 'clubs/club_detail.html', {'club': club, 'posts': posts})


# views.py
@login_required
def club_create(request):
    if request.method == 'POST':
        form = ClubForm(request.POST)
        if form.is_valid():
            club = form.save(commit=False)
            club.creator = request.user
            club.save()
            club.members.add(request.user)
            return redirect('clubs:club_detail', club_id=club.id)
    else:
        form = ClubForm()
    return render(request, 'clubs/club_create.html', {'form': form})


@login_required
def club_post_create(request, club_id):
    club = get_object_or_404(Club, id=club_id)

    if request.user not in club.members.all():
        return redirect('clubs:club_detail', club_id=club.id)

    if request.method == 'POST':
        form = ClubPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.club = club
            post.author = request.user
            post.save()
            return redirect('clubs:club_detail', club_id=club.id)
    else:
        form = ClubPostForm()

    return render(request, 'clubs/club_post_create.html', {'form': form, 'club': club})


@login_required
def request_to_join(request, club_id):
    club = get_object_or_404(Club, id=club_id)

    if request.user in club.members.all():
        return redirect('clubs:club_list')

    # Check if they have already requested
    membership_request = ClubMembershipRequest.objects.filter(club=club, user=request.user, status='pending').exists()

    if not membership_request:
        # Create a membership request
        ClubMembershipRequest.objects.create(club=club, user=request.user)

    return redirect('clubs:club_list')



@login_required
def manage_membership_requests(request, club_id):
    club = get_object_or_404(Club, id=club_id)

    # Only the club creator (admin) can manage membership requests
    if request.user != club.creator:
        return redirect('clubs:club_detail', club_id=club.id)  # Non-admin users can't manage requests

    # Get all pending membership requests for the club
    membership_requests = ClubMembershipRequest.objects.filter(club=club, status='pending')

    if request.method == 'POST':
        request_id = request.POST.get('request_id')
        action = request.POST.get('action')
        membership_request = get_object_or_404(ClubMembershipRequest, id=request_id, club=club)

        if action == 'approve':
            # Approve the request, add user to the club members, and update status
            membership_request.status = 'approved'
            membership_request.save()
            club.members.add(membership_request.user)
        elif action == 'reject':
            # Reject the request and update status
            membership_request.status = 'rejected'
            membership_request.save()

        return redirect('clubs:manage_membership_requests', club_id=club.id)

    return render(request, 'clubs/manage_membership_requests.html', {
        'club': club,
        'membership_requests': membership_requests
    })

digital_library/events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Event

from .forms import EventForm

@login_required
def event_list(request):
    events = Event.objects.all()
    return render(request, 'events/event_list.html', {'events': events})

@login_required
def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    return render(request, 'events/event_detail.html', {'event': event})

@login_required
def join_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    event.participants.add(request.user)
    return redirect('events:event_detail', pk=event.pk)


@login_required
def create_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator = request.user
            event.save()
            return redirect('events:event_list')
    else:
        form = EventForm()
    return render(request, 'events/create_event.html', {'form': form})

digital_library/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

digital_library/templates/base.html
{% load static i18n %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}Library{% endblock title %}</title>
  <meta name="description" content="Digital Library for book exchange and clubs">
  <meta name="author" content="Your Name">

  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

  <!-- Favicon -->
  <link href="{% static 'img/logo/favicon.png' %}" rel="icon"/>

  <!-- Styles -->
  <link href="{% static 'css/vendor.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css"/>

  {% block css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  {% endblock %}
</head>
<body>

<div id="wrapper">
  {% block header %}
    <!-- Header Section -->
    <header id="header">
      <a href="javascript:void(0);" id="hamburger"><i class="icon ion-navicon"></i></a>

      <form action="{% url 'books:search_results' %}" method="GET" class="search-form">
        <div class="input-group">
          <button type="submit" class="btn"><i class="icon ion-ios-search-strong"></i></button>
          <input type="text" name="query" placeholder="Search books or clubs" class="form-control" required>
        </div>
      </form>


      <ul class="navbar ml-auto">
        {% if request.user.is_authenticated %}
          <li class="dropdown">
            <a href="javascript:void(0);" id="user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="user">
              {#              <li class="dropdown-item"><a href="{% url 'profile' %}">My Profile</a></li>#}
              <li class="dropdown-item"><a href="{% url 'account_logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li><a href="{% url 'account_login' %}">Login</a></li>
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </header>
  {% endblock header %}

  {% block aside %}
    <aside id="sidebar">
      <a href="{% url 'home' %}" class="navbar-brand">
        <img src="{% static 'img/logo/dark-logo.png' %}" id="dark-logo" alt="logo">
        <span>Digital Library</span>
      </a>

      <nav id="sidebar-nav">
        <ul>
          <li class="nav-head"><span class="head">Menu</span></li>
          <li><a href="{% url 'books:book_list' %}"><i class="icon ion-ios-book"></i>Books</a></li>
          <li><a href="{% url 'game:select_book' %}"><i class="icon ion-ios-game-controller-a"></i>Game</a></li>
          <li><a href="{% url 'clubs:club_list' %}"><i class="icon ion-ios-people"></i>Clubs</a></li>
          <li><a href="{% url 'events:event_list' %}"><i class="icon ion-ios-calendar"></i>Events</a></li>
          <li><a href="{% url 'archives:archive_list' %}"><i class="icon ion-archive"></i>Digital Archives</a></li>

          {#          <li><a href="{% url 'users:detail' user.username %}"><i class="icon ion-ios-person"></i>Profile</a></li>#}
          <li><a href="{% url 'books:profile_bookshelf' %}"><i class="icon ion-ios-bookmarks"></i>My bookshelf</a></li>
          {#          <li><a href="{% url 'books:finished_books' %}">My Finished Books</a></li>#}
        </ul>
      </nav>
    </aside>
  {% endblock aside %}

  {% block content %}
    <main id="page-wrapper">
      <div class="container-fluid">
        <!-- Dynamic Content Goes Here -->
        <div class="page-header">
          <h6 class="h6">Welcome to Digital Library</h6>
        </div>
        <div class="row">
          <!-- Content Blocks for Books, Clubs, Events, etc. -->
          {% block page_content %}

          {% endblock page_content %}
        </div>
      </div>
    </main>
  {% endblock content %}

  {% block modal %}{% endblock modal %}

  <!-- JavaScript -->
  {% block javascript %}
    <script src="{% static 'js/vendor.js' %}"></script>
    <script src="{% static 'js/base/custom.js' %}"></script>
  {% endblock javascript %}
</div>

</body>
</html>

digital_library/templates/error.html
{% extends "account/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Error" %}{% endblock %}

{% block content %}
  <main id="page-wrapper">
    <div class="container-fluid">
      <div class="page-header d-flex">
        <div class="heading page-header-item">
          <h6 class="h6">Error</h6>
        </div>
      </div>

      <div class="alert alert-danger">
        <h5>Error Occurred</h5>
        <p>{{ message }}</p>
      </div>

      <a href="{% url 'home' %}" class="btn btn-primary">Back to Home</a>
    </div>
  </main>
{% endblock %}