config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from digital_library.users.views import home_view
urlpatterns = [
    path("", home_view, name="home"),
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("digital_library.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    path('game/', include('digital_library.game.urls', namespace='game')),
    path('books/', include('digital_library.books.urls', namespace='books')),
    path('clubs/', include('digital_library.clubs.urls', namespace='clubs')),
    path('events/', include('digital_library.events.urls', namespace='events')),
    path('archives/', include('digital_library.archives.urls', namespace='archives')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

digital_library/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('search/', views.search_results, name='search_results'),

    path('create/', views.BookFormView.as_view(), name='book_create'),
    path('<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/update/', views.BookUpdateFormView.as_view(), name='book_update'),

    path('books/<int:book_id>/request/', views.create_exchange_request, name='create_exchange_request'),
    path('pending-requests/', views.pending_requests, name='pending_requests'),
    path('accept-request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject-request/<int:request_id>/', views.reject_request, name='reject_request'),

    path('shared-progress/', views.shared_progress, name='shared_progress'),
    path('finished-books/', views.finished_books, name='finished_books'),
    path('finished-books/remove/<int:book_id>/', views.remove_finished_book, name='remove_finished_book'),

    path('bookshelf/', views.profile_bookshelf, name='profile_bookshelf'),
    path('book/<int:book_id>/progress/', views.add_edit_progress, name='add_edit_progress'),
    path('book/<int:book_id>/finished/', views.add_to_finished_books, name='add_to_finished_books'),
    path('book/<int:book_id>/toggle_visibility/', views.toggle_visibility, name='toggle_visibility'),
    path('progress/<int:book_id>/toggle_visibility/', views.toggle_progress_visibility, name='toggle_progress_visibility'),

    path('<int:book_id>/discussions/start/', views.start_discussion, name='start_discussion'),
    path('<int:book_id>/discussions/', views.discussion_list, name='discussion_list'),
    path('<int:book_id>/discussions/<int:discussion_id>/', views.discussion_detail, name='discussion_detail'),
    path('discussions/<int:discussion_id>/comment/', views.add_comment, name='add_comment'),
    path('discussions/<int:discussion_id>/comment/<int:comment_id>/reply/', views.reply_comment, name='reply_comment'),

    # path('<int:id>/delete/', views.book_delete, name='book_delete'),
]

digital_library/clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('', views.club_list, name='club_list'),
    path('create/', views.club_create, name='club_create'),
    path('<int:club_id>/', views.club_detail, name='club_detail'),
    # path('<int:id>/update/', views.club_update, name='club_update'),
    # path('<int:id>/delete/', views.club_delete, name='club_delete'),
    path('<int:club_id>/post/create/', views.club_post_create, name='club_post_create'),
    path('<int:club_id>/request-to-join/', views.request_to_join, name='request_to_join'),
    path('<int:club_id>/manage-requests/', views.manage_membership_requests, name='manage_membership_requests'),
]

digital_library/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('select-book/', views.select_book, name='select_book'),
    path('<int:book_id>/<str:language>/ask/', views.ask_question, name='ask_question'),
    path('<int:book_id>/ask/', views.ask_local_question, name='ask_local_question'),
    path('submit-answer/', views.submit_answer, name='submit_answer'),
    path('result/', views.show_result, name='show_result'),
    path('restart/', views.restart_game, name='restart_game'),
    path('<int:book_id>/ratings/', views.view_ratings, name='view_ratings'),
    path('error/', views.error_page, name='error'),
]

digital_library/archives/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import DigitalArchive
from .forms import ArchiveForm  # You need to create this form


@login_required
def archive_list(request):
    query = request.GET.get('q')
    if query:
        archives = DigitalArchive.objects.filter(title__icontains=query)
    else:
        archives = DigitalArchive.objects.all()

    return render(request, 'archives/archive_list.html', {'archives': archives})


@login_required
def archive_detail(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    return render(request, 'archives/archive_detail.html', {'archive': archive})


@login_required
def archive_create(request):
    if request.method == 'POST':
        form = ArchiveForm(request.POST, request.FILES)
        if form.is_valid():
            archive = form.save(commit=False)
            archive.uploaded_by = request.user
            archive.save()
            return redirect('archives:archive_list')
    else:
        form = ArchiveForm()
    return render(request, 'archives/archive_create.html', {'form': form})


@login_required
def archive_update(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    if request.method == 'POST':
        form = ArchiveForm(request.POST, request.FILES, instance=archive)
        if form.is_valid():
            form.save()
            return redirect('archives:archive_detail', pk=archive.pk)
    else:
        form = ArchiveForm(instance=archive)
    return render(request, 'archives/archive_create.html', {'form': form})


@login_required
def archive_delete(request, pk):
    archive = get_object_or_404(DigitalArchive, pk=pk)
    if request.method == 'POST':
        archive.delete()
        return redirect('archive_list')
    return render(request, 'archives/archive_confirm_delete.html', {'archive': archive})

digital_library/books/views.py
from django.contrib.auth.decorators import login_required
from .models import Book, ExchangeRequest, UserFinishedBook, UserBookProgress, Discussion, Comment
from .forms import ExchangeRequestForm, BookForm, UpdateProgressForm, CommentForm, DiscussionForm

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from ..clubs.models import Club


class BookListView(ListView):
    template_name = 'books/book_list.html'
    model = Book
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books = Book.objects.filter(is_visible=True)
        context['books'] = books
        return context


class BookDetailView(DetailView):
    template_name = 'books/book_detail.html'  # Point to your book detail template
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = self.object
        return context


class BookFormView(LoginRequiredMixin, CreateView):
    form_class = BookForm
    template_name = 'books/book_form.html'  # Point to your book form template
    login_url = '/accounts/login/'  # Redirect to login if user is not authenticated

    def form_valid(self, form):
        book = form.save(commit=False)
        book.owner = self.request.user  # Set the logged-in user as the owner
        book.save()
        return redirect(reverse('books:book_list'))


class BookUpdateFormView(LoginRequiredMixin, UpdateView):
    form_class = BookForm
    template_name = 'books/book_form.html'  # Point to your book form template
    model = Book
    login_url = '/accounts/login/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.owner == self.request.user:  # Ensure only the owner can update the book
            self.object.save()
            return redirect(reverse('books:book_list'))
        else:
            return redirect(reverse('books:book_list'))


# @login_required
# def book_list(request):
#     books = Book.objects.filter(is_available=True).exclude(owner=request.user)
#     return render(request, 'books/book_list.html', {'books': books})
#
# @login_required
# def book_detail(request, pk):
#     book = get_object_or_404(Book, pk=pk)
#     return render(request, 'books/book_detail.html', {'book': book})

@login_required
def exchange_request(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = ExchangeRequestForm(request.POST)
        if form.is_valid():
            exchange_request = form.save(commit=False)
            exchange_request.book = book
            exchange_request.requester = request.user
            exchange_request.save()
            return redirect('book_list')
    else:
        form = ExchangeRequestForm()
    return render(request, 'books/exchange_request.html', {'form': form, 'book': book})


# def book_create(request):
#     if request.method == 'POST':
#         form = BookForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('books:book_list')  # Redirect to the book list after creating a book
#     else:
#         form = BookForm()
#
#     return render(request, 'books/book_form.html', {'form': form})


def track_book_progress(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    progress, created = UserBookProgress.objects.get_or_create(user=request.user, book=book)

    if request.method == 'POST':
        progress_value = request.POST.get('progress')
        share = request.POST.get('share', False)
        progress.progress = int(progress_value)
        progress.is_finished = True if int(progress_value) == 100 else False
        progress.shared = bool(share)
        progress.save()

        return redirect('user_books')  # Redirect to user books overview or detail page

    context = {
        'book': book,
        'progress': progress,
    }
    return render(request, 'books/track_progress.html', context)


@login_required
def shared_progress(request):
    shared_books = UserBookProgress.objects.filter(shared=True).select_related('user', 'book')
    context = {
        'shared_books': shared_books
    }
    return render(request, 'books/shared_progress.html', context)


@login_required
def finished_books(request):
    finished_books = UserFinishedBook.objects.filter(user=request.user)
    context = {
        'finished_books': finished_books
    }
    return render(request, 'books/finished_books.html', context)


@login_required
def profile_bookshelf(request):
    user = request.user
    progress_books = UserBookProgress.objects.filter(user=user)
    finished_books = UserFinishedBook.objects.filter(user=user)
    user_books = Book.objects.filter(owner=user)
    requests = ExchangeRequest.objects.filter(book__owner=request.user, accepted=False)

    context = {
        'progress_books': progress_books,
        'finished_books': finished_books,
        'user_books': user_books,
        'pending_requests': requests,
    }
    return render(request, 'books/profile_bookshelf.html', context)


@login_required
def add_edit_progress(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    progress, created = UserBookProgress.objects.get_or_create(user=request.user, book=book)

    if request.method == 'POST':
        form = UpdateProgressForm(request.POST, instance=progress)
        if form.is_valid():
            form.save()
            return redirect('books:profile_bookshelf')
    else:
        form = UpdateProgressForm(instance=progress)

    return render(request, 'books/add_edit_progress.html', {'form': form, 'book': book})


@login_required
def add_to_finished_books(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    UserFinishedBook.objects.get_or_create(user=request.user, book=book)
    return redirect('books:profile_bookshelf')


@login_required
def remove_finished_book(request, book_id):
    finished_book = get_object_or_404(UserFinishedBook, user=request.user, book_id=book_id)
    finished_book.delete()
    return redirect('books:profile_bookshelf')


@login_required
def toggle_visibility(request, book_id):
    book = get_object_or_404(Book, id=book_id, owner=request.user)
    book.is_visible = not book.is_visible
    book.save()
    return redirect('books:profile_bookshelf')


@login_required
def toggle_progress_visibility(request, book_id):
    progress_book = get_object_or_404(UserBookProgress, user=request.user, book_id=book_id)
    progress_book.toggle_visibility()
    return redirect('books:profile_bookshelf')


def search_results(request):
    query = request.GET.get('query')
    if query:
        books = Book.objects.filter(title__icontains=query)
        clubs = Club.objects.filter(name__icontains=query)
    else:
        books = Book.objects.none()
        clubs = Club.objects.none()

    context = {
        'query': query,
        'books': books,
        'clubs': clubs
    }
    return render(request, 'books/search_results.html', context)


@login_required
def create_exchange_request(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == 'POST':
        form = ExchangeRequestForm(request.POST)
        if form.is_valid():
            exchange_request = form.save(commit=False)
            exchange_request.book = book
            exchange_request.requester = request.user
            exchange_request.save()
            return redirect('books:book_list')
    else:
        form = ExchangeRequestForm()

    return render(request, 'books/exchange_request_form.html', {'form': form, 'book': book})


@login_required
def pending_requests(request):
    requests = ExchangeRequest.objects.filter(book__owner=request.user, accepted=False)
    return render(request, 'books/pending_requests.html', {'requests': requests})


@login_required
def accept_request(request, request_id):
    exchange_request = get_object_or_404(ExchangeRequest, id=request_id, book__owner=request.user)
    exchange_request.accepted = True
    exchange_request.save()
    UserBookProgress.objects.get_or_create(book=exchange_request.book, user=exchange_request.requester)
    return redirect('books:profile_bookshelf')


@login_required
def reject_request(request, request_id):
    exchange_request = get_object_or_404(ExchangeRequest, id=request_id, book__owner=request.user)
    exchange_request.delete()  # Rejecting deletes the request
    return redirect('books:profile_bookshelf')


@login_required
def start_discussion(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if request.method == 'POST':
        form = DiscussionForm(request.POST)
        if form.is_valid():
            discussion = form.save(commit=False)
            discussion.book = book
            discussion.created_by = request.user
            discussion.save()
            return redirect('books:discussion_detail', book_id=book.id, discussion_id=discussion.id)
    else:
        form = DiscussionForm()

    return render(request, 'books/start_discussion.html', {'form': form, 'book': book})


def discussion_list(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    discussions = book.discussions.all()
    return render(request, 'books/discussion_list.html', {'book': book, 'discussions': discussions})


def discussion_detail(request, book_id, discussion_id):
    discussion = get_object_or_404(Discussion, id=discussion_id, book_id=book_id)
    comments = discussion.comments.filter(parent__isnull=True)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.discussion = discussion

digital_library/templates/books/add_edit_progress.html
{% extends "account/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Update Progress" %}{% endblock %}

{% block content %}
<main id="page-wrapper">
  <div class="container-fluid">
    <h2>{% trans "Update Progress for" %} {{ book.title }}</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">{% trans "Save Progress" %}</button>
    </form>
  </div>
</main>
{% endblock %}

digital_library/templates/books/book_list.html
{% extends "account/base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Books" %}{% endblock %}

{% block content %}

  <!-- Begin | Page Content Wrapper -->
  <main id="page-wrapper">
    <!-- Begin | Main Container -->
    <div class="container-fluid">
      <!-- Begin | Page Header -->
      <div class="page-header d-flex">
        <div class="heading page-header-item">
          <h6 class="h6">Books</h6>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'books:book_list' %}">Books</a></li>
              <li class="breadcrumb-item active" aria-current="page">All Books</li>
            </ol>
          </nav>
        </div>
        <div class="page-header-item ml-auto">
          <a href="{% url 'books:book_create' %}" class="btn btn-primary">Add New Book</a>
        </div>
      </div>
      <!-- End | Page Header -->

      <!-- Begin | Row for Books -->
      <div class="row">
        {% for book in books %}
          <!-- Begin | Column -->
          <div class="col-lg-4">
            <!-- Begin | Book Card -->
            <div class="card card-shadow product card-h-100 p-3">
              <div class="product-img">
                <img src="
      {% if book.cover_image %}{{ book.cover_image.url }}{% else %}{% static 'img/products/1.jpg' %}{% endif %}"
                     alt="Book Cover">
                <ul class="product-option">
                  {% if book.owner == request.user %}
                    <li>
                      <a href="{% url 'books:book_update' book.id %}" data-toggle="tooltip" data-placement="top"
                         title="Edit Book"><i class="mi mi-edit"></i></a>
                    </li>
                    <li>
                      <a href="{% url 'books:add_edit_progress' book.id %}" data-toggle="tooltip" data-placement="top"
                         title="Track Progress"><i class="mi mi-track-changes"></i>
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'books:add_to_finished_books' book.id %}" data-toggle="tooltip"
                         data-placement="top" title="Finish Book"><i class="mi mi-check-circle"></i>
                      </a>
                    </li>
                  {% else %}
                    <li>
                      <a href="{% url 'books:create_exchange_request' book.id %}" data-toggle="tooltip"
                         data-placement="top" title="Request Exchange"><i class="mi mi-swap-horiz"></i>
                      </a>
                    </li>
                  {% endif %}
                  <li>
                    <a href="{% url 'books:discussion_list' book.id %}" data-toggle="tooltip" data-placement="top"
                       title="View Discussions"><i class="mi mi-message"></i></a>
                  </li>
                </ul>
              </div>
              <div class="product-desc">
                <span class="title-midd text-truncate">{{ book.title }}</span>
              </div>
              <!-- Play Game Button -->
              <div class="card-footer">
                <div class="d-flex justify-content-around mt-2">
                  <!-- Leaderboard Button -->
                  <a href="{% url 'game:view_ratings' book.id %}"
                     class="btn btn-success btn-sm d-flex align-items-center">
                    Leaderboard
                  </a>

                  <!-- Play Game Button -->
                  <a href="{% url 'game:ask_local_question' book.id %}"
                     class="btn btn-primary btn-sm d-flex align-items-center ml-2">
                    <i class="mi mi-gamepad"></i>
                    Play Game
                  </a>
                </div>

              </div>
            </div>

            <!-- End | Book Card -->
          </div>
          <!-- End | Column -->
        {% endfor %}
      </div>
      <!-- End | Row for Books -->

      <!-- Begin | Footer -->
      <footer class="text-center mb-4">
        © {{ current_year }} Digital Library
      </footer>
      <!-- End | Footer -->
    </div>
    <!-- End | Main Container -->
  </main>
  <!-- End | Page Content Wrapper -->

{% endblock %}

digital_library/templates/books/pending_requests.html
{% extends "account/base.html" %}
{% block head_title %}Pending Exchange Requests{% endblock %}

{% block content %}
  <main id="page-wrapper">
    <div class="container-fluid">
      <div class="page-header d-flex">
        <div class="heading page-header-item">
          <h6 class="h6">Pending Exchange Requests</h6>
        </div>
      </div>

      {% if requests %}
        <ul>
          {% for req in requests %}
            <li>
              Request from {{ req.requester.username }} for "{{ req.book.title }}"
              <p>{{ req.message }}</p>
              <a href="{% url 'books:accept_request' req.id %}" class="btn btn-success">Accept</a>
              <a href="{% url 'books:reject_request' req.id %}" class="btn btn-danger">Reject</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No pending requests.</p>
      {% endif %}
    </div>
  </main>
{% endblock %}

digital_library/templates/books/profile_bookshelf.html
{% extends "account/base.html" %}
{% load static i18n %}
{% load socialaccount %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block content %}

  <!-- Begin | Page Content Wrapper -->
  <main id="page-wrapper">
    <!-- Begin | Main Container -->
    <div class="container-fluid">
      <!-- Begin | Page Header -->
      <div class="page-header d-flex">
        <div class="heading page-header-item">
          <h6 class="h6">{% trans "Profile" %}</h6>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans "Dashboard" %}</a></li>
              <li class="breadcrumb-item active" aria-current="page">{% trans "Profile" %}</li>
            </ol>
          </nav>
        </div>
      </div>
      <!-- End | Page Header -->

      <!-- Begin | Row -->
      <div class="row">
        <!-- Begin | Profile Column -->
        <div class="col-lg-5">
          <!-- Begin | Card Profile -->
          <div class="card card-shadow card-profile">
            <div class="card-img"></div>
            <!-- Begin | User Profile -->
            <div class="user-profile">
              {% if request.user.profile_picture %}
                <img src="{{ request.user.profile_picture.url }}" alt="{{ request.user.username }}"
                     class="rounded-circle" width="40" height="40">
              {% else %}
                <img src="{% static 'img/anon.webp' %}" alt="{{ request.user.username }}"
                     class="rounded-circle" width="40" height="40">
              {% endif %}
              <span class="title-midd mb-0">{{ request.user.get_full_name }}</span>
              <span>{{ request.user.get_username }}</span>
            </div>
            <!-- End | User Profile -->
            <!-- Begin | Card Body -->
            <div class="card-body">
              <div class="row">
                <div class="col-4">
                  <span class="title-big">10k</span>
                  <span>{% trans "Followers" %}</span>
                </div>
                <div class="col-4">
                  <span class="title-big">6k</span>
                  <span>{% trans "Following" %}</span>
                </div>
                <div class="col-4">
                  <span class="title-big">15k</span>
                  <span>{% trans "Posts" %}</span>
                </div>
              </div>
            </div>
            <!-- End | Card Body -->
          </div>
          <!-- End | Card Profile -->

          <!-- Begin | Card Contact Info -->
          <div class="card card-shadow p-3">
            <ul>
              <li class="mb-3">
                <span class="title-small">{% trans "Email address" %}</span>
                <span>{{ request.user.email }}</span>
              </li>
              <li class="mb-3">
                <span class="title-small">{% trans "Phone number" %}</span>
                <span>{% if request.user.profile.phone %}{{ request.user.profile.phone }}{% else %}
                  {% trans "Not provided" %}{% endif %}</span>
              </li>
              <li class="mb-3">
                <span class="title-small">{% trans "Address" %}</span>
                <span>{% if request.user.profile.address %}{{ request.user.profile.address }}{% else %}
                  {% trans "Not provided" %}{% endif %}</span>
              </li>
            </ul>
          </div>
          <!-- End | Card Contact Info -->
        </div>
        <!-- End | Profile Column -->

        <!-- Begin | Column with Progress, Finished Books, and User Books -->
        <div class="col-lg-7">
          <!-- Begin | Books in Progress Card -->
          <div class="card card-shadow p-3 mb-3">
            <h6 class="h6 card-title">{% trans "Books in Progress" %}</h6>
            {% if progress_books %}
              <ul>
                {% for progress in progress_books %}
                  <li>
                    <strong>{{ progress.book.title }}</strong> - {{ progress.progress }}%
                    <progress value="{{ progress.progress }}" max="100"></progress>
                    <a href="{% url 'books:add_edit_progress' progress.book.id %}" class="btn btn-secondary btn-sm">
                      {% trans "Edit Progress" %}
                    </a>
                    <a href="{% url 'books:toggle_progress_visibility' progress.book.id %}" class="btn btn-sm
          {% if progress.shared %} btn-danger {% else %} btn-success {% endif %}">
                      {% if progress.shared %}
                        {% trans "Make Private" %}
                      {% else %}
                        {% trans "Make Public" %}
                      {% endif %}
                    </a>
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p>{% trans "No books in progress." %}</p>
            {% endif %}

          </div>
          <!-- End | Books in Progress Card -->

          <!-- Begin | Finished Books Card -->
          <div class="card card-shadow p-3 mb-3">
            <h6 class="h6 card-title">{% trans "Finished Books" %}</h6>
            {% if finished_books %}
              <ul>
                {% for finished in finished_books %}
                  <li>{{ finished.book.title }}
                    - {% trans "Finished on" %} {{ finished.finished_at|date:"d M, Y" }} <a
                      href="{% url 'books:remove_finished_book' finished.book.id %}" class="btn btn-danger btn-sm"
                      title="Remove from Finished Books">
                      <i class="icon ion-trash-b"></i></a>
                  </li>

                {% endfor %}
              </ul>
            {% else %}
              <p>{% trans "No finished books." %}</p>
            {% endif %}
          </div>
          <!-- End | Finished Books Card -->

          <!-- Begin | User's Books Card -->
          <div class="card card-shadow p-3 mb-3">
            <h6 class="h6 card-title">{% trans "Your Books" %}</h6>
            {% if user_books %}
              <ul>
                {% for book in user_books %}
                  <li>
                    {{ book.title }}
                    <a href="{% url 'books:toggle_visibility' book.id %}" class="btn btn-link">
                      <i class="icon {% if book.is_visible %}ion-checkmark{% else %}ion-close{% endif %}"></i>
                      {% if book.is_visible %}{% trans "Visible" %}{% else %}{% trans "Hidden" %}{% endif %}
                    </a>
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p>{% trans "You have not added any books." %}</p>
            {% endif %}
          </div>
          <!-- End | User's Books Card -->

          <div class="card card-shadow p-3 mb-3">
            <h6 class="h6 card-title">{% trans "Requests" %}</h6>
            {% if pending_requests %}
              <ul>
                {% for req in pending_requests %}
                  <li>
                    Request from {{ req.requester.username }} for "{{ req.book.title }}"
                    <p>{{ req.message }}</p>
                    <a href="{% url 'books:accept_request' req.id %}" class="btn btn-success">Accept</a>
                    <a href="{% url 'books:reject_request' req.id %}" class="btn btn-danger">Reject</a>
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p>No pending requests.</p>
            {% endif %}
          </div>

        </div>
        <!-- End | Column with Progress, Finished Books, and User Books -->
      </div>
      <!-- End | Row -->

      <!-- Begin | Footer -->
      <footer class="text-center mb-4">
        © 2024 Digital Library
      </footer>
      <!-- End | Footer -->
    </div>
    <!-- End | Main Container -->
  </main>
  <!-- End | Page Content Wrapper -->

{% endblock %}